### ISSUE TITLE
JDBC Source Connector unable to find table in Oracle custom schema

### ISSUE THREAD

**Issue by mroiter-larus** [confluentinc/kafka-connect-jdbc#1211]
Hi,

i'm currently using JDBC Connector 10.5.0 (downloaded from Confluent Hub) and i'm getting the following error:

```
java.sql.SQLSyntaxErrorException: ORA-00942: table or view does not exist
connect  | 
connect  | 	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:509)
connect  | 	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:461)
connect  | 	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1104)
connect  | 	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:553)
connect  | 	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:269)
connect  | 	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:655)
connect  | 	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:270)
connect  | 	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:91)
connect  | 	at oracle.jdbc.driver.T4CPreparedStatement.executeForDescribe(T4CPreparedStatement.java:807)
connect  | 	at oracle.jdbc.driver.OracleStatement.executeMaybeDescribe(OracleStatement.java:983)
connect  | 	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1168)
connect  | 	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3666)
connect  | 	at oracle.jdbc.driver.T4CPreparedStatement.executeInternal(T4CPreparedStatement.java:1426)
connect  | 	at oracle.jdbc.driver.OraclePreparedStatement.executeQuery(OraclePreparedStatement.java:3713)
connect  | 	at oracle.jdbc.driver.OraclePreparedStatementWrapper.executeQuery(OraclePreparedStatementWrapper.java:1167)
connect  | 	at io.confluent.connect.jdbc.source.TimestampIncrementingTableQuerier.executeQuery(TimestampIncrementingTableQuerier.java:210)
connect  | 	at io.confluent.connect.jdbc.source.TimestampIncrementingTableQuerier.maybeStartQuery(TimestampIncrementingTableQuerier.java:164)
connect  | 	at io.confluent.connect.jdbc.source.JdbcSourceTask.poll(JdbcSourceTask.java:413)
connect  | 	at org.apache.kafka.connect.runtime.WorkerSourceTask.poll(WorkerSourceTask.java:304)
connect  | 	at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:248)
connect  | 	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:188)
connect  | 	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:243)
connect  | 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
connect  | 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
connect  | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
connect  | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
connect  | 	at java.base/java.lang.Thread.run(Thread.java:829)
```

In my use-case i would like to keep two Oracle instances in-sync using JDBC Connector. My test environment is Dockerized and below you will find the `docker-compose.yml` i've used:

```
---
version: '3'

networks:
  demo:
    driver: bridge

services:

  zookeeper:
    image: confluentinc/cp-zookeeper
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - demo

  kafka:
    image: confluentinc/cp-kafka
    hostname: kafka
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    expose:
      - "29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,OUTSIDE://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: kafka:29092
      CONFLUENT_METRICS_REPORTER_ZOOKEEPER_CONNECT: zookeeper:2181
      CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 1
      CONFLUENT_METRICS_ENABLE: 'true'
      CONFLUENT_SUPPORT_CUSTOMER_ID: 'anonymous'
    networks:
      - demo

  connect:
    image: confluentinc/cp-kafka-connect
    hostname: connect
    container_name: connect
    depends_on:
      - zookeeper
      - kafka
    ports:
      - "8083:8083"
    volumes:
      - ./kafka-connect/plugins:/tmp/connect-plugins
    environment:
      CONNECT_LOG4J_APPENDER_STDOUT_LAYOUT_CONVERSIONPATTERN: "[%d] %p %X{connector.context}%m (%c:%L)%n"
      CONNECT_BOOTSTRAP_SERVERS: 'kafka:29092'
      CONNECT_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      CONNECT_REST_PORT: 8083
      CONNECT_REST_ADVERTISED_HOST_NAME: "connect"
      CONNECT_GROUP_ID: compose-connect-group
      CONNECT_CONFIG_STORAGE_TOPIC: docker-connect-configs
      CONNECT_OFFSET_STORAGE_TOPIC: docker-connect-offsets
      CONNECT_STATUS_STORAGE_TOPIC: docker-connect-status
      CONNECT_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_LOG4J_ROOT_LOGLEVEL: "INFO"
      CONNECT_LOG4J_LOGGERS: "org.apache.kafka.connect.runtime.rest=WARN,org.reflections=ERROR"
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: "1"
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: "1"
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: "1"
      CONNECT_PLUGIN_PATH: /usr/share/java,/tmp/connect-plugins
    networks:
      - demo

  oracleSource:
    image: store/oracle/database-enterprise:12.2.0.1
    hostname: oracleSource
    container_name: oracleSource
    depends_on:
      - zookeeper
      - kafka
      - connect
    environment:
      - DB_SID=dbdemo
      - DB_PDB=demopdb
    ports:
      - 1521:1521
    networks:
      - demo

  oracleTarget:
    image: store/oracle/database-enterprise:12.2.0.1
    hostname: oracleTarget
    container_name: oracleTarget
    depends_on:
      - zookeeper
      - kafka
      - connect
    environment:
      - DB_SID=dbdemo
      - DB_PDB=demopdb
    ports:
      - 1522:1521
    networks:
      - demo 
```

Here is the JSON configuration about my JDBC Source connector:

```
{
    "name": "oracleXeSource",
    "config": {
        "connector.class": "io.confluent.connect.jdbc.JdbcSourceConnector",
        "connection.url": "jdbc:oracle:thin:@oracleSource:1521/demopdb.localdomain",
        "connection.user": "test",
        "connection.password": "test",
        "schema.pattern": "test",
        "catalog.pattern": "",
        "topic.prefix": "oracle_",
        "mode": "timestamp+incrementing",
        "table.types": "TABLE,VIEW",
        "incrementing.column.name": "id",
        "timestamp.column.name": "last_update",
        "table.whitelist": "test",
        "validate.non.null": false,
        "poll.interval.ms": 2000,
        "table.poll.interval.ms": 10000,
        "dialect.name": "OracleDatabaseDialect",
        "key.converter": "org.apache.kafka.connect.json.JsonConverter",
        "value.converter": "org.apache.kafka.connect.json.JsonConverter"
    }
}
```

I'm using ojbc8.jar (version 19.15.0.0.1 downloaded at the following link: https://download.oracle.com/otn-pub/otn_software/jdbc/1915-OAuth2/ojdbc8.jar) which should be compatible with Oracle 12.2 as documented [here](https://www.oracle.com/database/technologies/appdev/jdbc-downloads.html). 

Before starting the connector i have manually created the `test` table into the `test` schema by running the following sql commands via sqlplus cli:

```
alter session set container=demopdb;
create user test identified by test;
GRANT ALL PRIVILEGES TO test;
alter session set current_schema=test;
create table test (id NUMBER GENERATED BY DEFAULT AS IDENTITY, name varchar2(255), last_update TIMESTAMP NOT NULL, primary key (id));
```

To verify that the table is correctly created i've configured a Dbeaver connection to the `oracleSource` instance and it exists as expected. Here is a screenshot:

<img width="371" alt="Screenshot 2022-06-28 at 12 54 57" src="https://user-images.githubusercontent.com/12952543/176162471-dff3f4a4-0354-4fa2-92d7-291037a0a230.png">

and here is my connection settings:

<img width="651" alt="Screenshot 2022-06-28 at 15 03 50" src="https://user-images.githubusercontent.com/12952543/176185471-3ce9dc8a-d43f-4654-b844-79c7d2652408.png">

According to Kafka Connect logs it seems that JDBC Connector can't find the `test` table. In fact, the query created by the connector is:

```
SELECT * FROM "[]" WHERE "[]"."last_update" < ? AND (("[]"."last_update" = ? AND "[]"."id" > ?) OR "[]"."last_update" > ?) ORDER BY "[]"."last_update","[]"."id" ASC
```

As you can see, the table in the FROM and WHERE clauses is empty. I suppose the JDBC connector is not connecting to the correct schema even if i've set `"schema.pattern": "test"` in my JSON configuration.

Any suggestion on what am i doing wrong will be really appreciated.

Mauro
