### ISSUE TITLE
Cannot run Kafka connect on Debug Mode

### ISSUE THREAD

**Issue by Rahul7794** [confluentinc/kafka-connect-jdbc#900]
I am running JDBC source connector which pulls the data from MySQL to Kafka. 
The docker-compose file looks like
```
version: "3"
services:
  connect:
    build:
      context: .
      dockerfile: mysql-connector-dockerfile
    volumes:
      - .:/src:cached
    network_mode: host
    environment:
      CONNECT_REST_PORT: 8084
      CONNECT_PLUGIN_PATH: "/usr/share/java"
      CONNECT_LOG4J_OPTS: "-Dlog4j.configuration=file://etc/kafka/connect-log4j.properties"
      CONNECT_LOG4J_ROOT_LOGLEVEL: "TRACE"
      CONNECT_TOOLS_LOG4J_LOGLEVEL: "TRACE"
      CLASSPATH: /usr/share/java/monitoring-interceptors/monitoring-interceptors-5.3.0.jar
      KAFKA_HEAP_OPTS: "-Xms256M -Xmx6G"
      CONNECT_BOOTSTRAP_SERVERS: broker:9092
    command: connect-standalone /src/connect-standalone.properties /src/connect.properties
```
The docker file looks like:
```
FROM confluentinc/cp-kafka-connect:latest

# Install mysql driver
WORKDIR /tmp/
RUN curl -k -SL "http://dev.mysql.com/get/Downloads/Connector-J/mysql-connector-java-5.1.48.tar.gz" | tar -xz
RUN mv mysql-connector-java-5.1.48/mysql-connector-java-5.1.48-bin.jar /usr/share/java/kafka-connect-jdbc/

WORKDIR /src/

COPY . .

```
My connector config looks like

```
name=source_rebate

connector.class=io.confluent.connect.jdbc.JdbcSourceConnector
key.converter=org.apache.kafka.connect.storage.StringConverter
value.converter=org.apache.kafka.connect.json.JsonConverter
key.converter.schemas.enable=false
value.converter.schemas.enable=false
connection.url=jdbc:mysql://localhost:3306/sample
connection.user=root
connection.password=password
tasks.max=2
mode=bulk
batch.max.rows=100
offset.flush.interval.ms=5000
producer.buffer.memory=2097152
offset.flush.timeout.ms=300000
topic.prefix=rebate
query=SELECT * from sample where date >= '2020-08-05' limit 100
```
Once I do docker-compose up somehow it throwing an error saying `could not flush the offset, timeout`. I just want to enable debug logging so that I can trace the error. Any help would be much appreciated.
